#!/bin/bash

state="/home/yumio/.dotfiles/hypr/mouselockstate"
booleanvalue="false"

if [[ -f ${state} ]]; then
     booleanvalue=$(cat ${state})
fi

if [[ ${booleanvalue} == "true" ]]; then
     wlr-randr --output eDP-1 --pos 1920,0
     echo "false" > ${state}
else
     wlr-randr --output eDP-1 --pos 2000,0
     echo "true" > ${state}
fi
